title: The Brain Dump!
email: collinfarr2@gmail.com
description: <a href='/index'> Home </a> | <a href='/articles'> My Posts </a> | <a href='mailto:collinfarr2@gmail.com'>Email</a> | <a href='https://twitter.com/CollinFarr'> Twitter </a>
url: "http://itscollin.github.io"
theme: jekyll-theme-slate
